wasmd:
  image:
    repository: cosmwasm/wasmd
    tag: v0.40.1
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: '1000m'
      memory: '1024Mi'
    requests:
      cpu: '1000m'
      memory: '1024Mi'

nodeSelector: {}

tolerations: []

affinity: {}
